import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/sidebar/app-sidebar";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { InsightProvider } from "./context/context";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SidebarProvider>
					<AppSidebar />
					<SidebarTrigger />
					<InsightProvider>
						<div className="min-h-screen bg-background font-sans antialiased max-w-2xl mx-auto py-8 sm:py-16 px-8 space-y-8 py-8">
							{children}
						</div>
					</InsightProvider>
				</SidebarProvider>
			</body>
		</html>
	);
}
